intern_portal/comcodes/urls.py
from django.urls import path
from . import views

app_name = 'comcodes'

urlpatterns = [
    path('', views.index, name='index'),
    path('new_code/', views.add_typecode, name='new_code'),
    path('new_proposal/', views.create_proposal, name='new_proposal'),
    path('typecode_list/', views.typecode_list, name='typecode_list'),
    path('proposal_list/', views.proposal_list, name='proposal_list'),
    path('proposal_list/<int:proposal_id>/', views.proposal_detail, name='proposal_detail'),
    path('generatepdf', views.generate_pdf, name='generate_pdf'),
]

intern_portal/intern_portal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('comcodes.urls', namespace='comcodes')),
]

intern_portal/comcodes/models.py
from django.db import models
from django.db.models.signals import pre_save, post_save, m2m_changed
from django.dispatch import receiver
from django.utils import timezone


class TypeCode(models.Model):
    CHOICES = (
        ('ABB', 'ABB'),
        ('Danfoss', 'Danfoss'),
        ('VACON', 'VACON'),
        ('ONI', 'ONI'),
        ('Schneider', 'Schneider'),
    )
    name = models.TextField(
        max_length=150,
        verbose_name='Наименование или типовой код',
    )
    code = models.TextField(
        max_length=150,
        verbose_name='Код вендора'
    )
    vendor = models.CharField(
        max_length=30,
        choices=CHOICES,
    )
    price = models.FloatField(
        verbose_name='Стоимость, валюта'
    )

    def __repr__(self):
        return self.name
    
    def __str__(self):
        return f'{self.name} ({self.code})'


class Proposal(models.Model):
    typecodes = models.ManyToManyField(
        TypeCode,
        through='TypeCodeInProposal',
        verbose_name='Типовой код',
        related_name='typecodes'
    )

    amount = models.FloatField(
        verbose_name='Сумма КП, валюта',
        default=0
    )
    prop_id = models.TextField(
        verbose_name='Номер коммерческого предложения',
        unique=True
    )
    company = models.CharField(
        max_length=500,
        verbose_name='Название организации',
        default=None
    )
    person = models.TextField(
        verbose_name='Контактное лицо',
        default=None
    )
    supply_per = models.TextField(
        verbose_name='Срок поставки',
        default=None
    )
    payment = models.TextField(
        verbose_name='Условия оплаты',
        default=None
    )
    publication_date = models.DateTimeField(
        'Дата создания',
        auto_now=True,
    )   

    def __repr__(self):
        return self.prop_id
    
    def __str__(self):
        return self.prop_id

@receiver(post_save, sender=Proposal)
def generate_prop_id(sender, instance, created, **kwargs):
    if created and not instance.prop_id:
        if not instance.publication_date:
            instance.publication_date = timezone.now()
        date_part = instance.publication_date.astimezone(timezone.get_current_timezone()).strftime('%d%m%y')
        count = Proposal.objects.filter(publication_date__date=instance.publication_date.date(), prop_id__contains=f'{date_part}-').count() + 1
        while Proposal.objects.filter(prop_id=f'{date_part}-{count}').exists():
            count += 1
        instance.prop_id = f'{date_part}-{count}'
        instance.save()


class TypeCodeInProposal(models.Model):
    typecodes = models.ForeignKey(
        TypeCode,
        on_delete=models.CASCADE,
        verbose_name='Типовые коды',
        blank=False,
        null=False
    )
    proposal = models.ForeignKey(
        Proposal,
        on_delete=models.CASCADE,
        verbose_name='Коммерческое предложение',
        null=True,
        related_name='typecode_in_proposals'
    )
    qty = models.IntegerField(
        verbose_name='Количество'
    )

    def __str__(self):
        return f'{self.typecodes} в "{self.proposal}"'
    
    class Meta:
        ordering = ('-id',)
        verbose_name = 'Типовой код в КП'
        verbose_name_plural = 'Типовые коды в КП'
        constraints = (
            models.UniqueConstraint(
                fields=('proposal', 'typecodes'),
                name='unique_proposal_typecode'
            ),
        )

@receiver(post_save, sender=TypeCodeInProposal)
def generate_amount(sender, instance, created, **kwargs):
    if created:
        proposal = instance.proposal
        amount = 0
        typecodes = proposal.typecodes.all()
        for code in typecodes:
            typecode_in_proposal = TypeCodeInProposal.objects.get(proposal=proposal, typecodes=code)
            amount += code.price * typecode_in_proposal.qty
        proposal.amount = amount
        proposal.save()

intern_portal/comcodes/forms.py
from django import forms
from .models import TypeCode, Proposal, TypeCodeInProposal
from django.forms import inlineformset_factory, formset_factory
from django.forms.models import BaseInlineFormSet

class CodeForm(forms.ModelForm):
    class Meta:
        model = TypeCode
        fields = ('name', 'code', 'vendor', 'price')
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'code': forms.TextInput(attrs={'class': 'form-control'}),
            'vendor': forms.Select(attrs={'class': 'form-select'}),
            'price': forms.NumberInput(attrs={'class': 'form-control'})
        }

class TypeCodeInProposalForm(forms.ModelForm):
    typecodes = forms.ModelChoiceField(
        queryset=TypeCode.objects.all(),
        label='Типовой код',
        widget=forms.Select(attrs={'class': 'form-control'})
    )

    class Meta:
        model = TypeCodeInProposal
        fields = ['typecodes', 'qty']
        widgets = {
            'qty': forms.NumberInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'qty': 'Количество',
        }

class ProposalForm(forms.ModelForm):
    class Meta:
        model = Proposal
        fields = ['company', 'person', 'supply_per', 'payment',]
        labels = {
            'company': 'Название организации',
            'person': 'Контактное лицо',
            'supply_per': 'Срок поставки',
            'payment': 'Условия оплаты',
        }
        widgets = {
            'company': forms.TextInput(attrs={'class': 'form-control'}),
            'person': forms.TextInput(attrs={'class': 'form-control'}),
            'supply_per': forms.TextInput(attrs={'class': 'form-control'}),
            'payment': forms.TextInput(attrs={'class': 'form-control'}),
        }

# TypeCodeInProposalFormSet = inlineformset_factory(
#     Proposal,
#     TypeCodeInProposal,
#     form=TypeCodeInProposalForm,
#     extra=1,
#     can_delete=True,
#     can_delete_extra=True,
# )

TypeCodeInProposalFormSet = formset_factory(TypeCodeInProposalForm, extra=1)

intern_portal/comcodes/views.py
from django.shortcuts import render, redirect
from django.shortcuts import render, get_object_or_404
import os
from comcodes.models import TypeCode, Proposal, TypeCodeInProposal
from django.core.paginator import Paginator
from .forms import CodeForm, ProposalForm, TypeCodeInProposalFormSet
from django.http import HttpResponseRedirect, FileResponse
import io
from django.template.defaultfilters import date as date_filter
from django.conf import settings
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import A4
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
import reportlab.rl_config
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Image, Spacer, Paragraph
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from PIL import Image as PILImage
from reportlab.lib.units import cm
reportlab.rl_config.warnOnMissingFontGlyphs = 0


QTY1 = 10
QTY2 = 20


def index(request):
    title = 'Норд Индастриз - внутренний портал'
    proposals = Proposal.objects.all().order_by('-id')[:10]
    paginator = Paginator(proposals, QTY1)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'title': title,
        'proposals': proposals,
    }
    return render(request, 'comcodes/index.html', context)


def typecode_list(request):
    typecodes = TypeCode.objects.all().order_by('-id')
    paginator = Paginator(typecodes, QTY2)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'typecodes': typecodes,
        'page_obj': page_obj,
    }
    return render(request, 'comcodes/typecode_list.html', context)


def proposal_list(request):
    title = 'Коммерческие предложения'
    prop_list = Proposal.objects.all().order_by('-id')
    paginator = Paginator(prop_list, QTY2)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'title': title,
    }
    return render(request, 'comcodes/proposal_list.html', context)


def proposal_detail(request, proposal_id):
    proposal = get_object_or_404(Proposal, pk=proposal_id)
    form = ProposalForm(request.POST or None)
    
    if request.method == 'POST':
        if request.POST.get('download_pdf'):
            pdf_response = generate_pdf(request, proposal)
            return pdf_response    
    context = {
        'proposal': proposal,
        'form': form,
    }
    return render(request, 'comcodes/proposal_detail.html', context)


def generate_pdf(request, proposal):
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, rightMargin=20, leftMargin=20, topMargin=30, bottomMargin=30)
    story = []

    pdfmetrics.registerFont(TTFont('DejaVuSans', os.path.join(settings.BASE_DIR, 'static', 'fonts', 'DejaVuSans.ttf')))

    # Создание стилей
    styles = {
        'default': ParagraphStyle(
            'normal',
            fontName='DejaVuSans',
            fontSize=8,
            alignment=0,
            leading=12,
        ),
        'header1': ParagraphStyle(
            'header',
            fontName='DejaVuSans',
            fontSize=12,
            alignment=0,
            leading=14,
            textColor=colors.black,
        ),
        'header2': ParagraphStyle(
            'header',
            fontName='DejaVuSans',
            fontSize=10,
            alignment=0,
            leading=14,
            textColor=colors.black,
        ),
    }

    # Получение данных из модели Proposal
    table_data = [
        [Paragraph('№', styles['header2']),
         Paragraph('Наименование оборудования или код', styles['header2']),
         Paragraph('Код вендора', styles['header2']),
         Paragraph('Кол-во, шт.', styles['header2']),
         Paragraph('Стоимость без учёта НДС, рубли', styles['header2']),
         Paragraph('Сумма без учёта НДС, рубли', styles['header2'])],
    ]


    # Добавление данных из связанных с Proposal моделей TypeCode и TypeCodeInProposal в таблицу
    for i, typecode_in_proposal in enumerate(proposal.typecode_in_proposals.all(), start=1):
        typecode_info = [
            str(i),
            Paragraph(typecode_in_proposal.typecodes.name, styles['default']),
            Paragraph(typecode_in_proposal.typecodes.code, styles['default']),
            str(typecode_in_proposal.qty),
            str(typecode_in_proposal.typecodes.price),
            str(typecode_in_proposal.qty * typecode_in_proposal.typecodes.price),
        ]
        table_data.append(typecode_info)

    # Создание таблицы
    table_style = TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, -1), 'DejaVuSans'),
        ('FONTSIZE', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (-1, -1), 10),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.black),
    ])
    table = Table(table_data, colWidths=[0.5 * cm, 6.5 * cm, 2.5 * cm, 1.8 * cm, 3 * cm, 3.5 * cm], style=table_style)
    # Открытие изображения с использованием PIL.Image
    image_path = os.path.join(settings.BASE_DIR, 'static', 'images', 'top.png')
    img = Image(image_path, width=16.37 * cm, height=4.31 * cm)
    story.append(img)

    # Создание строки с использованием элемента Paragraph для даты
    date_paragraph = Paragraph(f'Дата: {proposal.publication_date.strftime("%d.%m.%Y")}', styles['default'])

    story.append(date_paragraph)
    story.append(Spacer(1, 0.2 * cm))

    # Создание строки с использованием элемента Paragraph для заголовка коммерческого предложения
    prop_id_paragraph = Paragraph(f'Коммерческое предложение {proposal.prop_id}', styles['header1'])
    story.append(prop_id_paragraph)
    story.append(Spacer(1, 1.5 * cm))

    # Добавление таблицы в историю
    story.append(table)

    # Генерация документа
    doc.build(story)

    buf.seek(0)

    filename = f'КП {proposal.prop_id}.pdf'
    return FileResponse(buf, as_attachment=True, filename=filename)


def add_typecode(request):
    if request.method == 'POST':
        form = CodeForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/new_code')
    else:
        form = CodeForm()
    return render(request, 'comcodes/create_code.html', {'form': form})


def create_proposal(request):
    form = ProposalForm()
    formset = TypeCodeInProposalFormSet(prefix='typecodes', data=request.POST or None)

    if request.method == 'POST':
        form = ProposalForm(request.POST)
        formset = TypeCodeInProposalFormSet(request.POST, prefix='typecodes')

        if form.is_valid() and formset.is_valid():
            proposal = form.save()
            for form_data in reversed(formset.forms):
                if form_data.cleaned_data:
                    typecode = form_data.cleaned_data['typecodes']
                    qty = form_data.cleaned_data['qty']
                    TypeCodeInProposal.objects.create(proposal=proposal, typecodes=typecode, qty=qty)
            return HttpResponseRedirect('/new_proposal')

    context = {
        'form': form,
        'formset': formset,
    }
    return render(request, 'comcodes/create_proposal.html', context)

intern_portal/templates/comcodes/create_code.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
      <div class="container py-5">
        <h1>{% block name %}Новый типовой код{% endblock%}</h1>
        <form method='post'>
          {% csrf_token %}
          {{ form.as_p }}
          <button type='submit' class="btn btn-primary">Добавить</button>
        </form>
      </div>
{% endblock %}

intern_portal/templates/comcodes/create_proposal.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="card mb-3">
<h3 class="card-header" style="text-align:center;">Коммерческое предложение {{ proposal.prop_id }}</h3>
</div>
<br></br>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}

    <table class="table form-table table-bordered table-sm">
      <thead class="text-center">
        <tr>
          <th>Типовой код</th>
          <th>Количество</th>
        </tr>
      </thead>
      <tbody id="formset-body">
        {{ formset.management_form }}
        {% for form_data in formset %}
          <tr>
            <td>
              {{ form_data.typecodes }}
            </td>
            <td>
              {{ form_data.qty }}
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

    <a href="#" id="add-variant-button" class="btn btn-secondary">Добавить код</a>

    <button type="submit" class="btn btn-primary">Создать</button>
  </form>

  <script id="typecodes-template" type="text/template">
    <tr>
      <td>
        {{ formset.empty_form.typecodes }}
      </td>
      <td>
        {{ formset.empty_form.qty }}
      </td>
    </tr>
  </script>

  {% block extra_script_bottom %}
    {% comment %} <script src="https://code.jquery.com/jquery-3.7.0.min.js" integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script> {% endcomment %}
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script>

        $('#add-variant-button').click(function(ev) {
            ev.preventDefault();
            var count = $('#formset-body tr').children().length;
            var tmplMarkup = $('#typecodes-template').html();
            var compiledTmpl = tmplMarkup.replace(/__prefix__/g, count);
            $('#formset-body').append(compiledTmpl);
    
            // update form count
            $('#id_typecodes-TOTAL_FORMS').attr('value', count+1);
        });
    </script>
  {% endblock %}
{% endblock %}

intern_portal/templates/comcodes/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
      <div class="container py-5">
        <div class="d-flex justify-content-between">
          <a class="btn btn-primary btn-lg flex-fill" href="{% url 'comcodes:new_code' %}" style="text-decoration: none; color: white;">
              Новый типовой код
          </a>
          
          <a class="btn btn-primary btn-lg flex-fill" href="{% url 'comcodes:new_proposal' %}" style="text-decoration: none; color: white;">
              Новое коммерческое предложение
          </a>
        </div>
        <br></br>
        <div class="card mb-3">
          <h3 class="card-header" style="text-align:center;">Последние коммерческие предложения{{ proposal.prop_id }}</h3>
        </div>
        <br></br>
        {% if proposals %}
        <table class="table table-hover">
          <thead>
            <tr>
              <th class="text-center" scope="col">Номер коммерческого предложения</th>
              <th class="text-center" scope="col">Организация</th>
              <th class="text-center" scope="col">Сумма, валюта</th>
              <th class="text-center" scope="col">Дата создания</th>
            </tr>
          </thead>
          <tbody>
            {% for proposal in proposals %}
            <tr>
              <td class="text-center">{{ proposal.prop_id }}</td>
              <td class="text-center">{{ proposal.company }}</td>
              <td class="text-center">{{ proposal.amount }}</td>
              <td class="text-center">{{ proposal.publication_date|date:"d.m.y H:i" }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        {% else %}
        <p>Нет коммерческих предложений</p>
        {% endif %}
{% endblock %}

intern_portal/templates/comcodes/proposal_detail.html
{% extends "base.html" %}
  {% block title %}КП {{ proposal.prop_id }}{% endblock %}
  {% block name %}{% endblock%}
  {% block content %}
    <div class="card mb-3">
      <h3 class="card-header">Коммерческое предложение {{ proposal.prop_id }}</h3>      
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <div class="card-body">
            <h5 class="card-title">{{  proposal.company   }}</h5>
            <p class="lead">Организация</p>
          </div>
        </li>
        <li class="list-group-item">
          <div class="card-body">
            <h5 class="card-title">{{  proposal.person  }}</h5>
            <p class="lead">Контактное лицо</p>
          </div>
        </li>
        <li class="list-group-item">
          <div class="card-body">
            <p style="font-size: 20px">{{  proposal.supply_per }}</p>
            <p class="lead">Срок поставки</p>
          </div>
        </li>
        <li class="list-group-item">
          <div class="card-body">
            <p style="font-size: 20px">{{  proposal.payment }}</p>
            <p class="lead">Условия оплаты</p>
          </div>
        </li>
        <li class="list-group-item">
          <div class="card-body">
            <p style="font-size: 20px">
              {% for typecode_in_proposal in proposal.typecode_in_proposals.all %}
              <strong>{{ typecode_in_proposal.typecodes.name }} ({{ typecode_in_proposal.typecodes.code }})</strong> в количестве {{ typecode_in_proposal.qty }} шт.<br>
              {% endfor %}
            </p>
            {% comment %} {% for typecode_in_proposal in proposal.typecode_in_proposals.all %}
              <strong>{{ typecode_in_proposal.typecodes.name }}</strong> в количестве {{ typecode_in_proposal.qty }} шт.<br>
            {% endfor %} {% endcomment %}
            <p class="lead">Типовые коды</p>
          </div>
        </li>
        <li class="list-group-item">
          <div class="card-body">
            <p style="font-size: 20px">{{  proposal.amount }} ¥</p>
            <p class="lead">Сумма коммерческого предложения (валюта)</p>
          </div>
        </li>
        <li class="list-group-item">
          <div class="card-body">
            <p style="font-size: 20px">{{  proposal.amount }} руб.</p>
            <p class="lead">Сумма коммерческого предложения</p>
          </div>
        </li>
      </ul>
      {% comment %} <div class="card-body"> {% endcomment %}
        {% comment %} <a href="#" class="card-link">Редактировать</a> {% endcomment %}
        {% comment %} <a href="{% url 'comcodes:generate_pdf' %}" class="card-link">Скачать бесплатно без регистрации и СМС</a> {% endcomment %}
      {% comment %} </div> {% endcomment %}

      
      <div class="card-footer text-muted">
        Создано: {{ proposal.publication_date|date:"d.m.y H:i" }}
      </div>
    </div>
    <form method="POST">
      {% csrf_token %}
      <!-- Добавьте другие поля формы, если необходимо -->
      <input type="submit" class="btn btn-primary" name="download_pdf" value="Скачать в PDF">
    </form>
{% endblock %}

intern_portal/templates/comcodes/proposal_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
      <div class="container py-5">
        <div class="card mb-3">
          <h3 class="card-header" style="text-align:center;">Коммерческие предложения {{ proposal.prop_id }}</h3>
          </div>
        <br><br>
        {% if page_obj %}
        <table class="table table-hover">
          <thead>
            <tr>
              <th class="text-center" scope="col">Номер коммерческого предложения</th>
              <th class="text-center" scope="col">Организация</th>
              <th class="text-center" scope="col">Сумма, ¥</th>
              <th class="text-center" scope="col">Дата создания</th>
              <th class="text-center" scope="col"></th>
              {% comment %} <th class="text-center" scope="col">Подробно</th> {% endcomment %}

            </tr>
          </thead>
          <tbody>
            {% for proposal in page_obj %}
            <tr>
              <td class="text-center">{{ proposal.prop_id }}</td>
              <td class="text-center">{{ proposal.company }}</td>
              <td class="text-center">{{ proposal.amount }}</td>
              <td class="text-center">{{ proposal.publication_date|date:"d.m.y H:i" }}</td>
              <td class="text-center">
                <a href="{% url 'comcodes:proposal_detail' proposal.pk %}"> Подробно </a><br>
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        {% else %}
        <p>Нет коммерческих предложений</p>
        {% endif %}
      {% include 'includes/paginator.html' %}
{% endblock %}

intern_portal/templates/comcodes/typecode_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
      <div class="container py-5">
        <div class="card mb-3">
          <h3 class="card-header" style="text-align:center;">Типовые коды {{ proposal.prop_id }}</h3>
        </div>
        <br><br>
        {% if page_obj %}
        <table class="table table-hover">
          <thead>
            <tr>
              <th class="text-center" scope="col">Наименование</th>
              <th class="text-center" scope="col">Вендор</th>
              <th class="text-center" scope="col">Код вендора</th>
              <th class="text-center" scope="col">Стоимость, валюта</th>
            </tr>
          </thead>
          <tbody>
            {% for typecode in page_obj %}
            <tr>
              <td class="text-center">{{ typecode.name }}</td>
              <td class="text-center">{{ typecode.vendor }}</td>
              <td class="text-center">{{ typecode.code }}</td>
              <td class="text-center">{{ typecode.price }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        {% else %}
        <p>Нет типовых кодов</p>
        {% endif %}
        {% include 'includes/paginator.html' %}
{% endblock %}